### ISSUE TITLE
[TASK] Report Macro

### ISSUE THREAD

**Issue by Tjemmmic** [tangle-network/gadget#263]
# Overview

The report! procedural macro is designed for defining reporting functions within a Blueprint. These functions are responsible for cross-chain reporting tasks, such as slashing, rather than completing specific jobs or tasks. The macro supports multiple parameters, providing flexibility across different contexts.

## General

- [x] params - Specifies the input parameters for the report function
- [x] result - Defines the expected output of the report function (use _ if no result is needed).
- [x] report_type - Classifies the type of report being generated (e.g., job or qos).
- [x] job_id - Associates the report with a specific job or task by ID, linking reports to a relevant jobs if applicable
- [x] interval - Defines how often the report is generated (e.g., how many seconds between reports).
- [x] metric_thresholds - Specifies any thresholds for the report
- [x] verifier - Identifies the Smart Contract or on-chain verifier used to validate the report (currently for EVM).
- [x] skip_codegen - Optional boolean parameter that skips code generation if the developer wants to customize the event handler.

## Event Handler

- [x] Options between `Tangle` or `Evm`, handling reports correctly based on the chain type

## Testing

- [ ] Integration test on Local Tangle Testnet
- [ ] Integration test on Local Evm Testnet

**Comment by drewstone** [comment]
Consider that jobs/reports are identical and duplicate job under the `report` name to deduplicate code if possible.
