### ISSUE TITLE
[TASK] Different Base options for creating AVS Blueprints (ECDSA/BLS)

### ISSUE THREAD

**Issue by Tjemmmic** [tangle-network/gadget#266]
# Overview

When a developer is creating a Blueprint, we want the developer to be able to choose between targets. Each target will change the "starting point" of the generated blueprint.
``` bash
gadget blueprint create --avs bls
gadget blueprint create --avs ecdsa
```

## Checklist
- [ ] ECDSA Template
- [ ] BLS Template

**Comment by Tjemmmic** [comment]
@shekohex Something like this had been discussed in the past. Let me know your thoughts here, though. Feel free to edit this completely, as well.

**Comment by drewstone** [comment]
And Eigenlayer (`--protocol eigenlayer` or `--protocol tangle [default]`)

**Comment by shekohex** [comment]
That's for the CLI, we can add the protocol as an option.
For the template, that's easy, we could configure it to have different bases. I will work on adding support to EL on the template.
