### ISSUE TITLE
[TASK] Improving Tangle node usage in Gadget SDK testing

### ISSUE THREAD

**Issue by drewstone** [tangle-network/gadget#305]
# Overview
Current testing requires running `run_standalone.sh` script which spawns 5 tangle testnet nodes. This is not something that seems needed for all cases and it's not configurable in any way. It is true that operators do not need to be validators. Therefore, we really only need 1 node running for many cases (probably maybe even all cases).

If we need a gadget setup that requires > 1 node, we should just spawn "operators" that are not validators. These operators should be endowed balances in the single node testnet. These operators should be able to run the blueprint manager client software. This marks a clear path to running an operator node that is NOT a validator.

- [x] Ensure that testing flows on SDK use the minimal amount of validator nodes
- [x] Use non-validating operators when spawning testing nodes in multi-party blueprint testing

**Comment by tbraun96** [comment]
Agreed, this should work with a single node
