### ISSUE TITLE
[TASK] Fix release workflow

### ISSUE THREAD

**Issue by Serial-ATA** [tangle-network/gadget#372]
# Overview

The release workflow isn't working as expected at the moment:

* The workflow **always fails on main** (https://github.com/tangle-network/gadget/actions/workflows/release-plz.yml)
* It seems like it just isn't picking up changes for `gadget-sdk`? The other crates work fine.
* Can we map crate names such that a commit message scope of "sdk" maps to "gadget-sdk"?
	* `feat(sdk)` vs `feat(gadget-sdk)`

### What's needed of us

* Using conventional commits in general
	* This even applies to squashed commits
* Correctly marking things as breaking: `feat!:` vs `feat:`
* Splitting up our PRs
	* At the moment, a lot of the PRs end up touching things outside of their scope.
* **Adding scopes to commit messages**
	* This is probably the biggest one, this is needed to indicate which changelog to put the changes in.
- [x] #388

**Comment by shekohex** [comment]
Could you also please include #388
