### ISSUE TITLE
[TASK] Make `blueprint-test-utils` publishable

### ISSUE THREAD

**Issue by shekohex** [tangle-network/gadget#395]
- Improve docs
- Improve README for `blueprint-test-utils`
- Fix any clippy lints.

This needed as we build more and more blueprints, and we want this default testing infra to be included in the blueprint template.

**Comment by Serial-ATA** [comment]
Emphasis on improving the docs. Right now, only 9 items have doc comments (and they're mostly just a repetition of the function name!)
