### ISSUE TITLE
[TASK] Blueprint must specify deployment target

### ISSUE THREAD

**Issue by drewstone** [tangle-network/gadget#412]
# Overview
Currently I don't know where we are specifying whether a blueprint gadget/instance is meant to be run natively, from docker, or from another target environment. This task should implement this as well as add support for the deployment targets supported in the blueprint manager.

**Comment by drewstone** [comment]
We could consider putting it directly in the main?
- `#[sdk::main(env, DockerDeployment)]`, `#[sdk::main(env, NativeDeployment)]`, `#[sdk::main(env, SgxDeployment)]`
- We could add it to the TOML, as part of the blueprint creation CLI flow? `cargo tangle blueprint create --name <...> --target <...>
- Feedback @tbraun96 @shekohex @Serial-ATA

**Comment by shekohex** [comment]
It's currently declared in your Cargo.toml. that's when you build your blueprint it will be generated in your `blueprint.json` file.
