### ISSUE TITLE
[TASK] MPC refactor: add common functions to context derive

### ISSUE THREAD

**Issue by tbraun96** [tangle-network/gadget#495]
Now that we've built multiple MPCs, duplicated code can be abstracted away inside the SDK and test utils.

Various MPC-related functions could be added as auto-generated context functions

e.g.,

```rust
#[derive(Mpc)]
struct MyContext { // ... }
// ...
fn my_job(context: MyContext) {
    let (i, operators) = context.get_operators_and_self_party_index();
    // ...
}
```

As for testing, we can have the initialization handle much of the repetitive boilerplate. Afterward, there may be room for a macro to easily define tests, especially MPC-specific macros that often store keys locally using a call ID, and that call ID needs to be funneled into the next job (e.g., keygen -> signing) in order to retrieve data from the local store.

**Comment by drewstone** [comment]
I would rather build this as a custom MPC context @tbraun96, we shouldn't add too many things directly on the env.
